version: '3.8'

services:
  quickbite-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quickbite-dashboard
    ports:
      - "8081:80"
    restart: unless-stopped
